cluster.name: bitergia_elasticsearch

#transport.tcp.port : 9310
http.bind_host: _eth0:ipv4_
network.host: _eth0:ipv4_

readonlyrest:
    enable: true
    response_if_req_forbidden: <h1>Forbidden</h1>

    access_control_rules:

    - name: "::bitergia FULL access::"
      auth_key: bitergia:bitergia
      type: allow

    - name: "::RO KIBANA (anonymous)::"
      type: allow
      kibana_access: ro
      indices: [".kibana", "index1"]

    users:

    - username: bitergia
      auth_key: bitergia # auth_key is good for testing but replace it with auth_key_sha1 for production!
      groups: ["admin"]

    - username: client1
      auth_key: client1 # auth_key is good for testing but replace it with auth_key_sha1 for production!
      groups: ["client1"]
